# Generated by Django 2.0 on 2018-09-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='avatar',
            new_name='avator',
        ),
    ]
